#Config for Villager In A Bucket
#'enable-zombie-villager' should the ability to pick up Zombie Villagers in buckets be enabled. Default true
#
#Sat Jul 11 13:46:54 UTC 2026
enable-zombie-villager=true
