#Config for Villager In A Bucket
#'enable-zombie-villager' should the ability to pick up Zombie Villagers in buckets be enabled. Default true
#
#Thu Jul 09 14:36:10 UTC 2026
enable-zombie-villager=true
